[tool.poetry]
name = "tssml"
version = "0.1.0"
description = "Environment for predicting TSS with ML models"
authors = ["Kostas Andreadis <kandread@umass.edu>", "Ted Langhorst <tmlanghorst@umass.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jax = "^0.4.25"
equinox = "^0.11.3"
notebook = "^7.1.2"
optax = "^0.2.1"
ipython = "^8.22.2"
matplotlib = "^3.8.3"
seaborn = "^0.13.2"
pandas = "^2.2.1"
pyarrow = "^15.0.2"
ipympl = "^0.9.3"
tqdm = "^4.66.2"
tensorflow = "^2.16.1"
tensorboard = "^2.16.2"
geopandas = "^0.14.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
